### ISSUE TITLE
Support PS5 + XBox Series X pads

### ISSUE THREAD

**Issue by tortoisedoc** [emscripten-ports/SDL2#135]
Hey, we would need to have SDL bumped to 2.0.12 for support for newer PS5 / XBOX Series X gamepads.
If there is anything that could be helped with?

**Comment by Daft-Freak** [comment]
Updating to 2.0.12 won't have much effect on controller support for the emscripten backend, since everything goes through the JS Gamepad APIs.

**Comment by tortoisedoc** [comment]
@Daft-Freak  yes, reason being that safari on latest iOS (at the time of writing) recognizes the pad, but the name is not correct (returns PID / VID). But I guess that's also part of browser support perhaps.

**Comment by Daft-Freak** [comment]
Looks like we [use the Gamepad API's `id` field as the name](https://github.com/emscripten-ports/SDL2/blob/2695e113f0878e49d7ac3f4953417f51d0ee6e0e/src/joystick/emscripten/SDL_sysjoystick.c#L63), so the name is entirely up to the browser.

We also only have [one mapping](https://github.com/emscripten-ports/SDL2/blob/2695e113f0878e49d7ac3f4953417f51d0ee6e0e/src/joystick/SDL_gamecontrollerdb.h#L604) as the browser is supposed to handle that too.


(It's been a while since I looked at this bit...)

**Comment by tortoisedoc** [comment]
@Daft-Freak indeed, the mapping is OK for our use-case. It seems iOS 14.5 is rolling in support for this now, so sorry for stirring up dust. Carry on! :)
