### ISSUE TITLE
Cannot create transparent GL context

### ISSUE THREAD

**Issue by mchiasson** [emscripten-ports/SDL2#48]
With this code, I would expect that I would be able to create a transparent overlay
```C++
    SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 8);
    context = SDL_GL_CreateContext(window);
```
Unfortunately, it remains opaque.

My current work around is to use `<emscripten/html5.h>` and do the following instead:
```C++
    EmscriptenWebGLContextAttributes attr;
    emscripten_webgl_init_context_attributes(&attr);
    attr.alpha = 1;
    attr.depth = attr.stencil = attr.antialias = attr.preserveDrawingBuffer = attr.preferLowPowerToHighPerformance = attr.failIfMajorPerformanceCaveat = 0;
    attr.enableExtensionsByDefault = 1;
    attr.premultipliedAlpha = 0;
    attr.majorVersion = 1;
    attr.minorVersion = 0;
    EMSCRIPTEN_WEBGL_CONTEXT_HANDLE ctx = emscripten_webgl_create_context(0, &attr);
    emscripten_webgl_make_context_current(ctx);
```

**Comment by Daft-Freak** [comment]
Probably the same as #45. We pass the attributes through to EGL but Emscripten's EGL implementation [currently ignores them](https://github.com/kripken/emscripten/blob/incoming/src/library_egl.js#L30).

**Comment by juj** [comment]
Acknowledged the problem. There's no issue to fix in SDL side, but we'll need to add this in Emscripten EGL side. We are currently in the middle of a big multithreading-enable flow of development in Emscripten, which rewrites EGL support there, see https://github.com/kripken/emscripten/pull/5580. After that PR lands, we can then directly hook in support to read the context attributes - the previous code used a bit clumsy initialization code due to historical reasons. @mchiasson, if you are not in a rush and the workaround you are using is satisfying, that's the best way to go for now.

**Comment by mchiasson** [comment]
yes, I am happy with my current workaround. Thank you guys!

**Comment by Daft-Freak** [comment]
Looks like this got fixed: https://github.com/kripken/emscripten/commit/1ec888135cd450dd226b5bfbd358b1a0443a8364
