### ISSUE TITLE
Official SDL2 vs emscripten-port's SDL2

### ISSUE THREAD

**Issue by mchiasson** [emscripten-ports/SDL2#49]
I tried the latest official SDL2 2.0.6 and cross-compiled it for emscripten, and it looks like it is working. I wanted to try it because they added support for joystick/gamepad for emscripten, and yes, gamepads are working (not that it is hard to do with <emscripten/html5.h>, but it's nice to have to maintain a single code line)

Are there any risks to use the official SDL2 instead? or is it a bad idea?

Thanks!

**Comment by Daft-Freak** [comment]
I regularly push changes to this repo upstream and there haven't been any since 2.0.6 was released, so there should be no missing features. The only real disadvantage is losing the ports integration (`-s USE_SDL=2`). 

I'm pretty sure [joystick](https://github.com/Daft-Freak/SDL-emscripten/pull/10) and [gamepad](
https://github.com/emscripten-ports/SDL2/commit/5e207639ecee8ec7d5a551aae31f3999998406fe) support has been there since the initial port though.

**Comment by mchiasson** [comment]
Not an issue for me since I've been already handling it on cmake side to cross-build SDL2 on other platforms already.

I remember from awhile ago that there were a lot of joystick/gamepad types missing from the headers. Maybe I imagined it because they all look there from looking at the git repo. I'm not sure what happened there. Must have been caffeine deprived or something. :laughing:
