### ISSUE TITLE
Abnormally large memory consumption during linking

### ISSUE THREAD

**Issue by iptq** [emscripten-ports/SDL2#74]
I'm building [a small Rust project](https://github.com/iptq/rust-wasm-canvas/) to be used as a test example with SDL2. But when the flag `-s USE_SDL=2` is passed to the linker, it suddenly starts consuming massive amounts of memory. Eventually my entire computer would freeze(I also tested on a different computer)

Any idea what could cause this issue?

**Comment by kripken** [comment]
Doesn't sound like a known issue. One unlikely possibility is that on machines with many cores but little memory, emcc will parallelize a lot (because it sees all the cores), and the system can run out of memory. But if you have a few hundred MB per core, that's more than enough.

 To investigate, one quick thing could be to pause the process (e.g. control-Z on linux) after it takes a lot of memory, but not enough to freeze you, then find out which process is responsible (e.g. top + shift-M on linux)

Building with EMCC_DEBUG=1 in the env may show some useful logging too.

**Comment by iptq** [comment]
what the heck, i rebuilt sdl2 and it works now. i'll let u know if i run into it again
