### ISSUE TITLE
Emscripten is linking against the wrong version?

### ISSUE THREAD

**Issue by a20eac1d** [emscripten-ports/SDL2#98]
Hey! Today I installed the latest emsdk and activated the Emscripten SDL2 port by using 

`-s USE_SDL=2`

Retrieving the SDL-Version in my code like this:

```
    SDL_version compiled_version;
    SDL_version linked_version;

    SDL_VERSION(&compiled_version);
    SDL_GetVersion(&linked_version);

    printf("Loading SDL version (compiled/linked): %u.%u.%u / %u.%u.%u\n",
        compiled_version.major, compiled_version.minor, compiled_version.patch,
        linked_version.major,   linked_version.minor,   linked_version.patch);
```

returns a different version on Emscripten than on Windows.
It seems like the Emscripten-Port is not update to date?

Windows: Loading SDL version (compiled/linked): 2.0.10 / **2.0.10**
Emscripten: Loading SDL version (compiled/linked): 2.0.10 / **2.0.9**

Is this to be expected?

Is it possible to link SDL2 manually so that I have the updated version available in Emscripten or do I have to wait for this repository to be updated?

Thank you!

**Comment by Daft-Freak** [comment]
Yes, we're still on 2.0.9. You can build upstream 2.0.10 (which is missing a few patches that I haven't pushed there yet), or [this branch](https://github.com/emscripten-ports/SDL2/tree/merge-2.0.10) (which is missing only the most recent change). You can switch to the branch by changing `TAG` in `tools/ports/sdl2.py` to the branch name. (It's not merged mainly because I haven't got round to testing it yet.)
